<img src="https://firebasestorage.googleapis.com/v0/b/deep-learning-crash-course.appspot.com/o/Logo.png?alt=media&token=06318ee3-d7a0-44a0-97ae-2c95f110e3ac" width="100" height="100" align="right"/>

## 2 Numpy Basics

## 2.1 Tensors and Numpy
<img src="https://firebasestorage.googleapis.com/v0/b/deep-learning-crash-course.appspot.com/o/2Numpy.png?alt=media&token=fc8f3815-66d0-47df-ab28-3d053c42e00e" width="200" height="200" align="right"/>

### <font color='Orange'> Tensors </font>
> <font size="3">**Mathematically, a tensor is a generalization of vectors and matrices. Within the context of TensorFlow, a tensor is considered as a multi-dimensional array.
<br>
<br>
With the use of <span style="background-color: #ECECEC; color:#0047bb">.numpy()</span> method, tensors can be explicilty converted to Numpy ndarrays objects into tf.Tensor objects. 
<br>
<br>
Similar to Numpy ndarray objects, tf.Tensor objects have a data type and a shape. Their mathematical operations are also similar to each other.
<br>
<br>
Unlike Numpy arrays, tf.Tensors can be backed by accelerator memory (GPU, TPU).**</font>

<font size="3">**TensorFlow offers a rich library of operations that consume and produce tf.Tensors, such as <span style="background-color: #ECECEC; color:#0047bb">tf.add</span>, <span style="background-color: #ECECEC; color:#0047bb">tf.matmul</span>, and <span style="background-color: #ECECEC; color:#0047bb">tf.linalg.inv</span>. These operations automatically convert native Python types.**</font>

Reference: https://www.tensorflow.org/about

### <font color='#176BEF'> Examples </font>
<hr style="border:2px solid #E1F6FF"> </hr>

In [ ]:
import tensorflow as tf

print(tf.add([1, 3], [5, 7]))

a = tf.constant([1, 3], shape=[1, 2])
b = tf.constant([5, 7], shape=[2, 1])

print(tf.matmul(a, b))

<hr style="border:2px solid #E1F6FF"> </hr>

## 2.2 Numpy - Axis, Rank & Dimension

<img src="https://firebasestorage.googleapis.com/v0/b/deep-learning-crash-course.appspot.com/o/2NumpyDimension.png?alt=media&token=07ff02d0-2499-40ff-b5de-46c03bcb01e7" width="600" align="center"/>

<font size="3">**In Python, List and Tuple can be stored in an array which can be 1D, 2D or even higher in dimension.
<br>
<br>
To improve the computational efficiency, Numpy requires each array with fixed structure. Such structure is defined by <span style="background-color: #ECECEC; color:#0047bb">.shape</span>.**</font>

### <font color='#176BEF'> Examples </font>
<hr style="border:2px solid #E1F6FF"> </hr>

In [ ]:
import numpy as np

arr_1D = np.array([1, 2, 3, 4])
print(arr_1D.shape)

arr_2D = np.array([[1, 2], [3, 4]])
print(arr_2D.shape)

<img src="https://firebasestorage.googleapis.com/v0/b/deep-learning-crash-course.appspot.com/o/2Numpy3Dexplain.png?alt=media&token=acf5b8be-e917-4e42-b89a-0fbd9a335cfd" width="600" align="center"/>

In [ ]:
arr_3D = np.array(   [   [[1, 2], [3, 4]]  ,  [[1, 2], [3, 4]]  ,  [[1, 2], [3, 4]]   ]   )
print(arr_3D.shape)

<hr style="border:2px solid #E1F6FF"> </hr>

<font size="5"><span style="background-color:#EA4335; color:white">&nbsp;!&nbsp;</span></font> 
<font size="3">**Elements from LEFT to RIGHT in the <span style="background-color: #ECECEC; color:#0047bb">.shape</span> represent the layers of array from OUTSIDE to INSIDE.**</font>
<br>
<br>
<font size="3">**For examples**</font>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.shape</span> (2,3) represents that there are 2 subarrays. Inside each of the 2 subarrays, there are 3 elements.**</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.shape</span> (2,3,4) represents that there are 2 subarrays. Inside each of the 2 subarrays, there are another 3 subarrays. Inside each of the 3 subarrays, there are 4 elements.**</font>

<font size="3">**In Numpy, dimensions are called axes. The number of axes is rank. In each of the axis, the number of elements are called dimension or length. For example, the <span style="background-color: #ECECEC; color:#0047bb">.shape</span> of a [[1,2,3], [4,5,6]] Numpy array is (2,3). Therefore, it has two axes. In the first axis (i.e. axis-0), it has 2 dimensions. In the second axis (i.e. axis-1), it has 3 dimensions.**</font>
    
<font size="3">**We typically refer 1D array as a vector and 2D array as a matrix. Hence, <span style="background-color: #ECECEC; color:#0047bb">.shape</span> (4,) is 4 dimensions vector and <span style="background-color: #ECECEC; color:#0047bb">.shape</span> (2,2) is a 2X2 matrix.**</font>
    
<font size="5"><span style="background-color:#EA4335; color:white">&nbsp;!&nbsp;</span></font>
<font size="3">**To avoid any confusion, we follow Numpy's logics, i.e. 1D is an array with 1 axis, 2D is an array with 2 axes, 3D is an array with 3 axes, and so on.**</font>

## 2.3 Numpy - Properties and Attributes

### <font color='Orange'> Numpy Properties </font>
> <font size="3">**Less memory and more efficient** - Numpy arrays require less memory and facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.</font>

> <font size="3">**Same data type** - The elements in a Numpy array are all required to be of the same data type, unlike Python lists or tuples.</font>

> <font size="3">**Same number of elements in each axis** - The number of elements in a Numpy arrays are all required to be the same, unlike Python lists or tuples.</font>

> <font size="3">**Fixed size at creation** - Numpy arrays have a fixed size at creation, unlike Python lists or tuples. Changing the size of an ndarray will create a new array and delete the original.</font>

Reference: https://numpy.org/doc/stable/user/whatisnumpy.html

### <font color='Orange'> Numpy Attributes </font>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.ndim</span>** - Number of array dimensions</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.shape</span>** - Tuple of array dimensions</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.size</span>** - Number of elements in the array</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.dtype</span>** - Return the data type of an array’s elements</font>

### <font color='#176BEF'> Examples </font>
<hr style="border:2px solid #E1F6FF"> </hr>

In [ ]:
import numpy as np

x = np.array(   [   [[1, 2], [3, 4]]  ,  [[1, 2], [3, 4]]  ,  [[1, 2], [3, 4]]   ]   )

print("The number of axis is", x.ndim)
print("The shape is", x.shape)
print("The size is", x.size)
print("The data type is", x.dtype)

<font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.astype</span>** casts an array’s elements to a specified type</font>

In [ ]:
y = x.astype('float')
print("The data type of x is", x.dtype)
print("The data type of y is", y.dtype)

<hr style="border:2px solid #E1F6FF"> </hr>

## 2.4 Numpy - Array Creation

<font size="3">**In Numpy, there are different mechanisms for creating arrays. This part will cover three commonly used methods for ndarray creation.**</font>

> <font size="3">**1. Converting Python sequences to Numpy arrays**</font>
<br>
> <font size="3">**2. Intrinsic Numpy array creation functions (e.g. arrange, ones, zeros, etc)**</font>
<br>
> <font size="3">**3. Replicating, joining, or mutating existing arrays**</font>

Reference: https://numpy.org/doc/stable/user/basics.creation.html

### <font color='#176BEF'> Examples </font>
<hr style="border:2px solid #E1F6FF"> </hr>

In [ ]:
import numpy as np

List = [1, 2, 3, 4]
print(List, type(List))

arr_1D = np.array([1, 2, 3, 4])
print(arr_1D, type(arr_1D))

In [ ]:
List_of_list = [[1, 2], [3, 4]]
print(List_of_list, type(List_of_list))

arr_2D = np.array([[1, 2], [3, 4]])
print(arr_2D, type(arr_2D))

In [ ]:
arr_range = np.arange(10)
print(arr_range, type(arr_range))

In [ ]:
arr_zeros = np.zeros((2,2))
print(arr_zeros, type(arr_zeros))

In [ ]:
arr_identity = np.eye(3)
print(arr_identity, type(arr_identity))

In [ ]:
# Create an array x, with a reference y
x = np.array([1, 2, 3])
y = x[1:3]
x += 10 
print('x =', x, '; y =', y)

In [ ]:
# Create an array x, with a copy z
x = np.array([1, 2, 3])
z = x[1:3].copy()
x += 10 
print('x =', x, '; z =', z)

In [ ]:
# Vectical Stack
arr_vs = np.vstack((y,z))
print(arr_vs, arr_vs.shape)

In [ ]:
# Horizontal Stack
arr_hs = np.hstack((y,z))
print(arr_hs, arr_hs.shape)

<hr style="border:2px solid #E1F6FF"> </hr>

## 2.5 Numpy - Indexing and Slicing

<font size="3">**Numpy array can be indexed using the standard Python syntax <span style="background-color: #ECECEC; color:#0047bb">x[obj]</span>. There are two main types of indexing available:  basic slicing and advanced indexing.**</font>

### <font color='Orange'> Basic slicing </font>
> <font size="3">**Basic slicing extends Python’s basic concept of slicing to N dimensions. It occurs when <span style="background-color: #ECECEC; color:#0047bb">obj</span> is a slice object (constructed by start:stop:step notation inside of brackets), an integer, or a tuple of slice objects and integers.**</font>
<br>
### <font color='Orange'> Advanced Indexing </font>
> <font size="3">**Advanced indexing is triggered when the selection object, <span style="background-color: #ECECEC; color:#0047bb">obj</span>, is a non-tuple sequence object, an ndarray (of data type integer or bool), or a tuple with at least one sequence object or ndarray (of data type integer or bool). There are two types of advanced indexing: integer and boolean.**</font>

Reference: https://numpy.org/doc/stable/reference/arrays.indexing.html

### <font color='#176BEF'> Examples </font>
<hr style="border:2px solid #E1F6FF"> </hr>

In [ ]:
# Basic slice syntax is i:j:k where i is the starting index, j is the stopping index, and k is the step (). 

import numpy as np

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print("Positive Slicing without Step", x[1:7])
print("Positive Slicing with Step", x[1:7:2])

In [ ]:
print("Negative Slicing without Step", x[-7:10])
print("Negative Slicing with Step", x[-7:10:2])

In [ ]:
print("Positive Slicing by Default i", x[:7])
print("Positive Slicing by Default j", x[7:])
print("Positive Slicing by Default k", x[1:7])

In [ ]:
# Advance slice syntax applies the row index and column index to choose for the corresponding elements.

x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

print(x)

print(x[0,0], x[1,1], x[2,0])

print(x[0][0], x[1][1], x[2][0])

print(x[[0, 1, 2], [0, 1, 0]], "   Remarks: this returns a list") 

In [ ]:
rows = np.array([[0,0], [2,2]])
columns = np.array([[0,1], [0,1]])

print(rows)

print(columns)

print(x[rows, columns], "   Remarks: this returns a nested list")

In [ ]:
conditions = np.where(x>2)

print(conditions, "   Remarks: this returns row index array and column index array")

print("x larger than 2 = ", x[conditions])

In [ ]:
print(np.where(x>2, x, np.nan), "   Remarks: this returns the same dimensionality by filling values")

<hr style="border:2px solid #E1F6FF"> </hr>

## 2.6 Numpy - Shape Manipulation

<font size="3">**An array has a shape given by the number of elements along each axis. The shape of an array can be changed with various commands, but the number of elements doesn't change.**</font>

><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.reshape</span>** - Gives a new shape to an array without changing its data.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.transpose</span>** - Reverse or permute the axes of an array; returns the modified array.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.vstack</span>** - Stack arrays in sequence vertically (row-wise).</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.hstack</span>** - Stack arrays in sequence horizontally (column-wise).</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.vsplit</span>** - Split an array into multiple sub-arrays vertically (row-wise).</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.hsplit</span>** - Split an array into multiple sub-arrays horizontally (column-wise).</font>
<br>

Reference: https://numpy.org/doc/stable/user/quickstart.html

### <font color='#176BEF'> Examples </font>
<hr style="border:2px solid #E1F6FF"> </hr>

In [ ]:
import numpy as np

x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
y = np.reshape(x, (2,6))
z = np.reshape(x, (3,4))

print("The original shape of x is" , x.shape)
print("The original shape of y is" , y.shape)
print("The original shape of z is" , z.shape)

In [ ]:
print("The tranpose of x is: \n" , np.transpose(x))

print("The tranpose of x is: \n" , np.transpose(x).shape)

In [ ]:
x = np.array([[0, 1, 2], [3, 4, 5]])
y = np.array([[6, 7, 8], [9, 10, 11]])

print(x, x.shape)
print(y, y.shape)

print("The result of horizontal stack: \n", np.hstack((x,y)), np.hstack((x,y)).shape)
print("The result of horizontal stack: \n", np.vstack((x,y)), np.vstack((x,y)).shape)

In [ ]:
x = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])

print("The result of horizontal split: \n", np.hsplit(x, 2))
print(np.hsplit(x, 2)[0])
print(np.hsplit(x, 2)[1])

In [ ]:
print("The result of vectical split: \n", np.vsplit(x, 2))
print(np.vsplit(x, 2)[0])
print(np.vsplit(x, 2)[1])


<hr style="border:2px solid #E1F6FF"> </hr>

## 2.7 Numpy - Element-wise VS Broadcasting

### <font color='Orange'> Element-wise </font>
> <font size="3">**Numpy operations are usually done on pairs of arrays on an element-wise basis. In the simplest case, the two arrays must have exactly the same shape.**</font>



In [ ]:
import numpy as np

x=np.array([1, 2, 3])
y=np.array([2, 2, 2])

print(x*y)

### <font color='Orange'> Broadcasting </font>
> <font size="3">**Numpy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation.**


In [ ]:
x=np.array([1, 2, 3])
y=2

print(x*y)

<font size="3">**Broadcasting two arrays together follows these rules:**
> <font size="3">**1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.**</font> <br>
> <font size="3">**2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.**</font><br>
> <font size="3">**3. The arrays can be broadcast together if they are compatible in all dimensions.**</font>  <br>
> <font size="3">**4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.**</font><br>
> <font size="3">**5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension**</font>

### <font color='#176BEF'> Examples </font>
<hr style="border:2px solid #E1F6FF"> </hr>

In [ ]:
import numpy as np

a = np.array([[0, 1], [2, 3]])
print(a.shape)

In [ ]:
b = np.array([4, 5])
print(b.shape)

> <font size="3">**1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.**</font> <br>

In [ ]:
b = np.array([[4, 5]])
print(b.shape)

print([b, b])

> <font size="3">**2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.**</font><br>
> <font size="3">**3. The arrays can be broadcast together if they are compatible in all dimensions.**</font>  <br>

In [ ]:
c=a+b
print(c)
print(c.shape)

> <font size="3">**4. After broadcasting, each array behaves as if it had shape equal to the element-wise maximum of shapes of the two input arrays.**</font><br>
> <font size="3">**5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension**</font>

In [ ]:
a = np.array([[[0, 1], [2, 3]], [[10, 11], [12, 13]]])
print(a.shape)

In [ ]:
b = np.array([4, 5])
print(b.shape)

> <font size="3">**1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.**</font> <br>

In [ ]:
b = np.array([[[4, 5]]])
print(b.shape)

> <font size="3">**2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.**</font><br>
> <font size="3">**3. The arrays can be broadcast together if they are compatible in all dimensions.**</font>  <br>

In [ ]:
c=a+b
print(c)
print(c.shape)

> <font size="3">**4. After broadcasting, each array behaves as if it had shape equal to the element-wise maximum of shapes of the two input arrays.**</font><br>
> <font size="3">**5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension**</font>

<img src="https://firebasestorage.googleapis.com/v0/b/deep-learning-crash-course.appspot.com/o/2NumpyBroadcasting.png?alt=media&token=aa6e483e-1a76-4c13-9ea3-8a60d7f309e6" width="800" align="center"/>

<hr style="border:2px solid #E1F6FF"> </hr>

## 2.8 Numpy - Aggregate and Statistical Functions

<font size="3">**Numpy has fast built-in aggregation and statistical functions for working on arrays, which includes:**</font>

><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.mean()</span>** - Compute the arithmetic mean along the specified axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.std()</span>** - Compute the standard deviation along the specified axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.var()</span>** - Compute the variance along the specified axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.sum()</span>** - Sum of array elements over a given axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.cumsum()</span>** - Return the cumulative sum of the elements along a given axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.cumprod()</span>** -  Return the cumulative product of elements along a given axis</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.min()</span>** - Return the minimum along a given axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.max()</span>** - Return the maximum along a given axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.argmin()</span>** - Returns the indices of the minimum values along an axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.argmax()</span>** - Returns the indices of the maximum values along an axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.all()</span>** - Test whether all array elements along a given axis evaluate to True.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.any()</span>** - Test whether any array element along a given axis evaluates to True.</font>
<br>

Reference: https://www.pythonprogramming.in/numpy-aggregate-and-statistical-functions.html

### <font color='#176BEF'> Examples </font>
<hr style="border:2px solid #E1F6FF"> </hr>

In [ ]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Mean:", np.mean(x))
print("Vertical Mean:", np.mean(x, axis=0))
print("Horizontal Mean:", np.mean(x, axis=1))

In [ ]:
print("Standard Deviation:", np.std(x))
print("Vertical Standard Deviation:", np.std(x, axis=0))
print("Horizontal Standard Deviation:", np.std(x, axis=1))

In [ ]:
print("Variance:", np.var(x))
print("Vertical Variance:", np.var(x, axis=0))
print("Horizontal Variance:", np.var(x, axis=1))

In [ ]:
print("Sum:", np.sum(x))
print("Vertical Sum:", np.sum(x, axis=0))
print("Horizontal Sum:", np.sum(x, axis=1))

In [ ]:
print("Product:", np.prod(x))
print("Vertical Product:", np.prod(x, axis=0))
print("Horizontal Product:", np.prod(x, axis=1))

In [ ]:
print(x)

print("Cumulative Sum:", np.cumsum(x))
print("Vertical Cumulative Sum:", np.cumsum(x, axis=0))
print("Horizontal Cumulative Sum:", np.cumsum(x, axis=1))

In [ ]:
print("Cumulative Product:", np.cumprod(x))
print("Vertical Cumulative Product:", np.cumprod(x, axis=0))
print("Horizontal Cumulative Product:", np.cumprod(x, axis=1))

In [ ]:
print("Minimum:", np.min(x))
print("Vertical Minimum:", np.min(x, axis=0))
print("Horizontal Minimum:", np.min(x, axis=1))

In [ ]:
print("Maximum:", np.max(x))
print("Vertical Maximum:", np.max(x, axis=0))
print("Horizontal Maximum:", np.max(x, axis=1))

In [ ]:
print("Indices of minimum:" , np.argmin(x))
print("Indices of vertical minimum:" , np.argmin(x, axis=0))
print("Indices of horizontal minimum:" , np.argmin(x, axis=1))

In [ ]:
print("Indices of maximum:" , np.argmax(x))
print("Indices of vertical maximum:" , np.argmax(x, axis=0))
print("Indices of horizontal maximum:" , np.argmax(x, axis=1))

<hr style="border:2px solid #E1F6FF"> </hr>

## 2.9 Numpy - Dot Product and Matrix Multiplication

<font size="3">**There are multiple options for performing dot product or matrix multiplication:**</font>

### <font color='Orange'> Element-wise Multiplication </font>
> <font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.multiply</span> <span style="background-color: #ECECEC; color:#0047bb">*</span> - A fundamental approach uses element-wise multiplication.**</font>

### <font color='Orange'> Dot Product </font>
> <font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.dot</span> - A dot product is the sum of products of values in two same-sized vectors.**</font>

### <font color='Orange'> Matrix Multiplication </font>
> <font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.matmul</span> <span style="background-color: #ECECEC; color:#0047bb">@</span> - A matrix multiplication is a matrix version of the dot product with two matrices.**</font>


Reference: https://mkang32.github.io/python/2020/08/30/numpy-matmul.html

### <font color='#176BEF'> Examples </font>
<hr style="border:2px solid #E1F6FF"> </hr>

In [20]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("Element-wise multiplication:", x*y)

Element-wise multiplication: [ 4 10 18]


In [21]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("Dot Product:", np.dot(x,y))

Dot Product: 32


In [22]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("Matrix Multiplication:", np.matmul(x,y))

Matrix Multiplication: 32


<font size="5"><span style="background-color:#EA4335; color:white">&nbsp;!&nbsp;</span></font> 
<font size="3">**When we deal with multi-dimensional arrays (N-D arrays with N>2),  <span style="background-color: #ECECEC; color:#0047bb">.dot</span> and <span style="background-color: #ECECEC; color:#0047bb">.matmul</span> provides different results.**</font>

In [23]:
x = np.array([[[1, 2], [3, 4]], [[1, 2], [3, 4]]])
print(x.shape)
y = np.array([[[1, 2], [3, 4]], [[1, 2], [3, 4]]])
print(y.shape)

(2, 2, 2)
(2, 2, 2)


In [24]:
z_dot = np.dot(x,y)
print(z_dot, z_dot.shape)

[[[[ 7 10]
   [ 7 10]]

  [[15 22]
   [15 22]]]


 [[[ 7 10]
   [ 7 10]]

  [[15 22]
   [15 22]]]] (2, 2, 2, 2)


<font size="3">**If x is an N-D array and y is an M-D array (where M>=2), <span style="background-color: #ECECEC; color:#0047bb">.dot</span> is a sum product over the last axis of x and the second-to-last axis of y.**</font>

> <font size="3">**dot(x, y)[i, j, k, m] = sum(x[i, j, :] * y[k, :, m])**</font>

In [25]:
z_mat = np.matmul(x,y)
print(z_mat, z_mat.shape)

[[[ 7 10]
  [15 22]]

 [[ 7 10]
  [15 22]]] (2, 2, 2)


<font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.matmul</span> function broadcasts the array like a stack of matrices as elements residing in the last two indexes respectively.**</font> 